import '@/styles/globals.css';
import Layout from '@/components/layout/layout';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Noto_Sans_KR, Noto_Serif_KR } from 'next/font/google';

const notoSansKr = Noto_Sans_KR({ weight: ['400', '500', '700'], subsets: ['latin'] });
const notoSerifKr = Noto_Serif_KR({ weight: ['200', '300', '400', '500', '600'], subsets: ['latin'] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>위잉위잉</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/mosquito.png" />
      </Head>
      <Layout className={`${notoSansKr.className} ${notoSerifKr}`}>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
