import '@/styles/globals.css';
import Layout from '@/components/layout/layout';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Noto_Sans_KR, Noto_Serif_KR, Oxanium } from 'next/font/google';
import localFont from 'next/font/local';

const blenderProBook = localFont({ src: './fonts/BlenderPro-Book.woff2' });

const notoSansKr = Noto_Sans_KR({ weight: ['400', '500', '700'], subsets: ['latin'] });
const notoSerifKr = Noto_Serif_KR({ weight: ['200', '300', '400', '500', '600'], subsets: ['latin'] });
const oxanium = Noto_Serif_KR({ weight: ['200', '300', '400', '500', '600'], subsets: ['latin'] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>위잉위잉</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="위잉위잉" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://mosquito-pixi.vercel.app/" />
        <meta property="og:image" content="https://mosquito-pixi.vercel.app/thumbnail.png" />
        <meta property="og:description" content="오늘 서울 모기지수는?" />
        <meta property="og:article:author" content="위잉위잉" />
        <link rel="icon" href="/mosquito.png" />
      </Head>
      <Layout className={`${notoSansKr.className} ${notoSerifKr} ${blenderProBook} ${oxanium}`}>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
